# Generated by Django 5.2.4 on 2025-08-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_released_movie_duration_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
